seed: 42

Project:
  name: 'WCR1d'
  checkpoint: False
  save_top_k: 1
  erase: True
  devices: 1
  accelerator: 'gpu'
  PATH: /home/ubuntu/myproject/wcr_neural_kan/save_files
  save_dir: 2d
  


data:
  dt: 0.001
  sample: 30000 
  dim: 2
  nt: 11
  T: 1
  plot_path: /home/ubuntu/myproject/wcr_neural_kan/result3D
  model: zx3
  frequency: 10

train:
  checkepoch: 10
  sigma_init: 0.3
  known_diffusion: False
  plotstep: [500,1000]
  testfunction: gauss
  gauss_number: 300
  bump_number: 1000
  sampling: SDE
  LMM: LMM_3
  sgd_ratio: 0.5
  epochs: 1000
  mean_samp_way: SDE_dist
  var_samp_way: dist
  error_type: uniform2d
  plot_type: 2d
  samp_coef: 
    lhs_ratio: 0.7
    variance_min: 0.3
    variance_max: 0.7

 
  

NN:
  dim: 2
  widthk: 50
  depthk: 1
  grid: 2
  activation: GeLU
  lr: 0.01
  gamma: 0.5
  step_size: 200
  weight_decay: 0.00001
  iter: 2000
  mode: KAN
  width: 100
  depth: 5
